function_name     = "dp-lmd-ue1-act-rds-initializer-dev"
user_env          = "dev"
inputs_file       = "dp-sec-db-ue1-af-activation-rds_users-dev"
account-function  = "compute"
account-name      = "compute-general-activation"
realm             = "general"
